name: PR Validation Workflow

on:
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: codeartifact-proxy

jobs:
  validate-pr:
    name: Validate Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.3

      - name: Run Tests
        shell: bash
        run: ( cd src ; go test -v )

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Verify Dockerfile
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          cache-to: "gha"
          cache-from: "gha"

      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          DEFAULT_BUMP: patch
          DEFAULT_BRANCH: ${{ github.head_ref }}
          RELEASE_BRANCHES: ${{ github.head_ref }}
          DRY_RUN: true

      - name: Replace TRACKED_GIT_VERSION
        shell: bash
        env:
          NEW_VERSION: ${{ steps.tag_version.outputs.new_tag }}
          FILE_PATH: main.tf
        run: |
          go run src/utils/replaceVersion.go

      - name: Commit Files
        id: commit
        uses: kassett/autocommit-changes@v1
        with:
          commit-message: "Updating tracked Git version in source code"
          branch: ${{ github.head_ref }}
          github-token: ${{ secrets.GITHUB_TOKEN }}