name: Merge to main

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: codeartifact-proxy
  IMAGE_PATH: ghcr.io/codeartifact-proxy

jobs:
  merge:
    name: Merge to main
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          DEFAULT_BUMP: patch

      - name: Push docker image
        uses: docker/build-push-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          context: .
          provenance: true
          push: true
          tags: "${{ env.IMAGE_PATH }}:latest,${{ env.IMAGE_PATH }}:${{ steps.tag_version.outputs.new_tag }}"
